#!/usr/bin/env python

from __future__ import print_function

from argparse import ArgumentParser
import sys


def main(args):
    args = parse_args(args)
    impl(args)


def parse_args(args):
    parser = ArgumentParser(description="scaffold for an argparse CLI")
    parser.add_argument("-p", "--print", help="print an arg", metavar='')
    if len(args) == 1:
        parser.print_help()
        sys.exit()
    return parser.parse_args()


def impl(args):
    print(args.print)

if __name__ == "__main__":
    main(sys.argv)
